language: java
jdk:
  - openjdk8

# 어느 브랜치가 푸시될 때 수행할지 지정
branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# 해당 디렉토리에 캐시, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sosokim9966@gmail.com

before_deploy:
  - zip -r JPA-Study
  - mkdir -p deploy
  - mv JPA-Study.zip deploy/JPA-Study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: @AWS_SECRET_KEY

    bucket: sosokim-springboot-build
    region: ap-northeast-2
    skip_cleanup: true